#!/usr/bin/env ruby

# Bundler setup
require 'rubygems'
require 'bundler/setup'

# Gem dependencies
require 'curb'
require 'twitter'

# Lib dependencies
require 'pathname'
require 'json'
require 'yaml'

# Add this directory to the LOAD_PATH
PATH = File.dirname(Pathname.new(__FILE__).realpath)
$:.unshift(PATH)

# Lappy files
require 'lib/Main'
require 'lib/Curler'
require 'lib/Tweeter'
require 'lib/Wordler'

# Process those arguments
Lappy::Main.new.process ARGV
