#!/usr/bin/env ruby

# Bundler setup
require 'rubygems'
require 'bundler/setup'

# Gem dependencies
require 'curb'

# Lappy files
require'./lib/Main'

# Process those arguments
lappy = Lappy::Main.new
lappy.process ARGV
